# config.yml

endpoints:
  ollama_chat: "http://localhost:8081/api/chat"
  ollama_embed: "http://localhost:8081/api/embed"
  ollama_generate: "http://localhost:8081/api/generate"

email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  username: "intellichat93@gmail.com"
  password: "tygx oxdj ztjc ygda"
  default_from_address: "intellichat93@gmail.com"
  cc_address: "cc_email@example.com"